#' Blend species predictions
#'
#' @description Function for merging the vegetation and soil based predictions.
#'
#' @param climate Matrix of the bioclimatic variables that is matched to the vegetation and/or soil matrices.
#' @param veg Vector of vegetation based predictions generated by the species_predict function.
#' @param soil Vector of soil based predictions generated by the species_predict function.
#'
#' @import Matrix
#'
#' @export
#'

blend_predict <- function(climate = NULL, veg = NULL, soil = NULL) {
    
    ##########################
    # Check for valid inputs #
    ##########################
    
    if(is.null(veg) & is.null(soil)) {
        
        stop("Need to define the species predictions.")
        
    }
    
    if(is.null(climate)) {
        
        stop("Need to define the climate information.")
        
    }
    
    ######################################
    # Align the veg and soil predictions #
    ######################################
    
    veg.pred <- data.frame(Cell = names(veg),
                           veg = veg)
    
    soil.pred <- data.frame(Cell = names(soil),
                            soil = soil)
    
    species.pred <- data.frame(Cell = rownames(climate),
                               wN = climate$wN,
                               wS = climate$wS)
    
    species.pred <- merge.data.frame(species.pred, veg.pred, by = "Cell", all = TRUE)
    species.pred <- merge.data.frame(species.pred, soil.pred, by = "Cell", all = TRUE)
    species.pred[is.na(species.pred)] <- 0
    cell.names <- species.pred$Cell
    
    # Create the blended prediction and return
    species.pred <- (species.pred$wN * species.pred$veg) + (species.pred$wS * species.pred$soil)
    names(species.pred) <- cell.names
    
    # Return the prediction
    return(species.pred)
    
}

